In [1]:
import pandas as pd
df = pd.read_csv("D:\SS DATA PROJECT\DATABASE.csv")
df.head()

,Po Placing Date,PO. No.,S.O. No.,Customer,Quality,NSR,VD/\nTPC,GSM,Width,X,Length,Grain,Qty. \nMt.,DISP,Pending Qty,Mill / QSC,Status
0,01-04-2025,SS2010,10895971,PHARMAX ART,SAFIRE XL PAC,76000,4000.0,290,58.5,X,91.5,LG,0.8,0.7440,0.06,Q,Complete
1,01-04-2025,SS2253,40292490,GRAPHIX ART,SAFIRE XL PAC,76000,4000.0,290,63.5,X,84.0,LG,1.9,1.9220,-0.02,Q,Complete
2,01-04-2025,SS2251,10895974,SAIN PACKAGING,PEARL XL PACKAGING,75000,4250.0,290,56.5,X,74.9,LG,1.8,1.7589,0.04,Q,Complete
3,01-04-2025,SS2251,40292495,SAIN PACKAGING,PEARL XL PACKAGING,75000,4250.0,340,53.3,X,74.9,LG,1.5,1.5640,-0.06,Q,Complete
4,02-04-2025,SS2262,40292549,SAIN PACKAGING,PEARL XL PACKAGING,75000,4250.0,290,62.0,X,56.0,SG,2.0,1.9291,0.07,Q,Complete

In [2]:
df.describe()

,S.O. No.,NSR,VD/\nTPC,GSM,Width,Length,Qty. \nMt.,DISP,Pending Qty
count,2.529000e+03,2529.000000,1888.000000,2529.000000,2529.000000,1926.000000,2529.000000,2529.000000,2529.000000
mean,1.934366e+07,80165.109529,2246.689619,241.420720,70.216449,84.215421,12.034520,11.955451,0.079055
std,1.338527e+07,20988.414184,1772.936870,109.841954,21.790641,13.905625,28.629338,27.763838,3.131395
min,1.089586e+07,40000.000000,500.000000,28.000000,30.000000,44.500000,0.300000,0.347300,-21.430000
25%,1.092050e+07,74000.000000,2000.000000,160.000000,58.500000,76.000000,2.500000,2.440200,-0.340000
50%,1.094027e+07,77000.000000,2000.000000,285.000000,63.500000,89.000000,5.000000,5.027400,0.000000
75%,4.029709e+07,81000.000000,2250.000000,310.000000,78.700000,93.300000,13.000000,13.167000,0.150000
max,8.487713e+07,189000.000000,11250.000000,450.000000,213.500000,137.200000,500.000000,495.777400,122.510000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2529 entries, 0 to 2528
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Po Placing Date  2529 non-null   object
 1   PO. No.          2529 non-null   object
 2   S.O. No.         2529 non-null   int64
 3   Customer         2529 non-null   object
 4   Quality          2529 non-null   object
 5    NSR             2529 non-null   int64
 6    VD/
TPC         1888 non-null   float64
 7   GSM              2529 non-null   int64
 8   Width            2529 non-null   float64
 9   X                1926 non-null   object
 10  Length           1926 non-null   float64
 11  Grain            2529 non-null   object
 12  Qty.
Mt.        2529 non-null   float64
 13  DISP             2529 non-null   float64
 14  Pending Qty      2529 non-null   float64
 15  Mill / QSC       2529 non-null   object
 16  Status           2529 non-null   object
dtypes: float64(6), int64(3), object(8)
memory usage: 336.0+ KB

In [4]:
df.tail()

,Po Placing Date,PO. No.,S.O. No.,Customer,Quality,NSR,VD/\nTPC,GSM,Width,X,Length,Grain,Qty. \nMt.,DISP,Pending Qty,Mill / QSC,Status
2524,21-03-2026,SS4343,10970371,SAPFOODPAK,INDOBEV 2 PE,120000,NaN,202,85.5,NaN,NaN,REEL,5.0,5.55050,-0.55,PARAS-POLY,Complete
2525,31-03-2026,SS4373,10970069,DJS PRINTER PVT LTD,INDOBEV 2 PE FSC,107000,NaN,327,87.0,X,64.0,SG,54.6,58.52694,-3.93,PARAS-POLY,Complete
2526,31-03-2026,SS4370,10976408,GLS FILMS INDUSTRIES,COATED BOARD CFK,100650,NaN,200,42.8,NaN,NaN,REEL,150.0,148.41100,1.59,M,Pending
2527,31-03-2026,SS4372,10970066,DJS PRINTER PVT LTD,INDOBEV 2 PE FSC,107000,NaN,252,99.0,X,58.0,SG,7.3,7.38050,-0.08,PARAS-POLY,Complete
2528,31-03-2026,SS4372,10970066,DJS PRINTER PVT LTD,INDOBEV 2 PE FSC,107000,NaN,252,80.0,X,67.0,SG,4.1,3.88800,0.21,PARAS-POLY,Complete

In [5]:
df.isnull().sum()

Po Placing Date      0
PO. No.              0
S.O. No.             0
Customer             0
Quality              0
 NSR                 0
 VD/\nTPC          641
GSM                  0
Width                0
X                  603
Length             603
Grain                0
Qty. \nMt.           0
DISP                 0
Pending Qty          0
Mill / QSC           0
Status               0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df["Customer"].value_counts()

Customer
Suneja Sons                   638
KAY ART PRINTER               162
DJS PRINTER PVT LTD           150
SAIN PACKAGING                135
GRAPHIX ART                   135
                             ...
SANTOSHI ENTERPRISES            1
SUPER INDIA PAPER PRODUCTS      1
SUNSHINE PRINTER                1
COLORTEX PRODUCTS               1
VINAYAK ENTERPRISES             1
Name: count, Length: 100, dtype: int64

In [8]:
df.fillna(0)

,Po Placing Date,PO. No.,S.O. No.,Customer,Quality,NSR,VD/\nTPC,GSM,Width,X,Length,Grain,Qty. \nMt.,DISP,Pending Qty,Mill / QSC,Status
0,01-04-2025,SS2010,10895971,PHARMAX ART,SAFIRE XL PAC,76000,4000.0,290,58.5,X,91.5,LG,0.8,0.74400,0.06,Q,Complete
1,01-04-2025,SS2253,40292490,GRAPHIX ART,SAFIRE XL PAC,76000,4000.0,290,63.5,X,84.0,LG,1.9,1.92200,-0.02,Q,Complete
2,01-04-2025,SS2251,10895974,SAIN PACKAGING,PEARL XL PACKAGING,75000,4250.0,290,56.5,X,74.9,LG,1.8,1.75890,0.04,Q,Complete
3,01-04-2025,SS2251,40292495,SAIN PACKAGING,PEARL XL PACKAGING,75000,4250.0,340,53.3,X,74.9,LG,1.5,1.56400,-0.06,Q,Complete
4,02-04-2025,SS2262,40292549,SAIN PACKAGING,PEARL XL PACKAGING,75000,4250.0,290,62.0,X,56.0,SG,2.0,1.92910,0.07,Q,Complete
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2524,21-03-2026,SS4343,10970371,SAPFOODPAK,INDOBEV 2 PE,120000,0.0,202,85.5,0,0.0,REEL,5.0,5.55050,-0.55,PARAS-POLY,Complete
2525,31-03-2026,SS4373,10970069,DJS PRINTER PVT LTD,INDOBEV 2 PE FSC,107000,0.0,327,87.0,X,64.0,SG,54.6,58.52694,-3.93,PARAS-POLY,Complete
2526,31-03-2026,SS4370,10976408,GLS FILMS INDUSTRIES,COATED BOARD CFK,100650,0.0,200,42.8,0,0.0,REEL,150.0,148.41100,1.59,M,Pending
2527,31-03-2026,SS4372,10970066,DJS PRINTER PVT LTD,INDOBEV 2 PE FSC,107000,0.0,252,99.0,X,58.0,SG,7.3,7.38050,-0.08,PARAS-POLY,Complete
2528,31-03-2026,SS4372,10970066,DJS PRINTER PVT LTD,INDOBEV 2 PE FSC,107000,0.0,252,80.0,X,67.0,SG,4.1,3.88800,0.21,PARAS-POLY,Complete

In [9]:
print(df['Po Placing Date'].head(10))

0    01-04-2025
1    01-04-2025
2    01-04-2025
3    01-04-2025
4    02-04-2025
5    02-04-2025
6    02-04-2025
7    01-04-2025
8    04-04-2025
9    04-04-2025
Name: Po Placing Date, dtype: object

In [10]:
df['Po Placing Date'] = pd.to_datetime(df['Po Placing Date'], format='%d-%m-%Y')

In [11]:
print(df.shape)

(2529, 17)

In [12]:
# Replace all spaces in column names with underscores
df.columns = df.columns.str.replace(' ', '_')
df.columns = df.columns.str.replace(' ', '')
df.columns = df.columns.str.replace('.', '')
df.columns = df.columns.str.replace('_VD/\nTPC_', 'VD_TPC')
df.columns = df.columns.str.replace('_NSR_', 'NSR')
df.columns = df.columns.str.replace('Mill_/_QSC', 'PLANT')
df.columns = df.columns.str.replace('Qty_\nMt_', 'QTY-MT')

In [13]:
print(df.columns)

Index(['Po_Placing_Date', 'PO_No', 'SO_No', 'Customer', 'Quality', 'NSR',
       'VD_TPC', 'GSM', 'Width', 'X', 'Length', 'Grain', 'QTY-MT', 'DISP',
       'Pending_Qty', 'PLANT', 'Status'],
      dtype='object')

In [14]:
df = df.drop(columns=['X'])

In [15]:
print(df.dtypes)

Po_Placing_Date    datetime64[ns]
PO_No                      object
SO_No                       int64
Customer                   object
Quality                    object
NSR                         int64
VD_TPC                    float64
GSM                         int64
Width                     float64
Length                    float64
Grain                      object
QTY-MT                    float64
DISP                      float64
Pending_Qty               float64
PLANT                      object
Status                     object
dtype: object

In [16]:
# Check total duplicates
print(f"Total duplicate rows: {df.duplicated().sum()}")

# Check duplicates by specific column (like PO_No)
print(f"Duplicate PO_No: {df.duplicated(subset=['PO_No']).sum()}")

# See the duplicate rows
print(df[df.duplicated(subset=['PO_No'], keep=False)])

Total duplicate rows: 0
Duplicate PO_No: 987
     Po_Placing_Date   PO_No     SO_No             Customer  \
2         2025-04-01  SS2251  10895974       SAIN PACKAGING
3         2025-04-01  SS2251  40292495       SAIN PACKAGING
4         2025-04-02  SS2262  40292549       SAIN PACKAGING
5         2025-04-02  SS2262  40292549       SAIN PACKAGING
6         2025-04-02  SS2262  40292549       SAIN PACKAGING
...              ...     ...       ...                  ...
2519      2026-03-11  SS4281  10964827      KAY ART PRINTER
2520      2026-03-11  SS4281  10964827      KAY ART PRINTER
2521      2026-02-11  SS4148  10960054           SAPFOODPAK
2527      2026-03-31  SS4372  10970066  DJS PRINTER PVT LTD
2528      2026-03-31  SS4372  10970066  DJS PRINTER PVT LTD

                 Quality     NSR  VD_TPC  GSM  Width  Length Grain  QTY-MT  \
2     PEARL XL PACKAGING   75000  4250.0  290   56.5    74.9    LG     1.8
3     PEARL XL PACKAGING   75000  4250.0  340   53.3    74.9    LG     1.5
4     PEARL XL PACKAGING   75000  4250.0  290   62.0    56.0    SG     2.0
5     PEARL XL PACKAGING   75000  4250.0  320   78.5    58.5    SG     2.5
6     PEARL XL PACKAGING   75000  4250.0  340   51.4    96.5    LG     1.9
...                  ...     ...     ...  ...    ...     ...   ...     ...
2519        PHARMA PRINT  120000  7000.0   38   63.5    91.5    LG     2.0
2520        PHARMA PRINT  120000  7000.0   38   58.5    91.5    LG     3.0
2521   INDOBEV BOARD 1PE  101500     NaN  177   77.5     NaN  REEL     5.0
2527    INDOBEV 2 PE FSC  107000     NaN  252   99.0    58.0    SG     7.3
2528    INDOBEV 2 PE FSC  107000     NaN  252   80.0    67.0    SG     4.1

         DISP  Pending_Qty       PLANT    Status
2     1.75890         0.04           Q  Complete
3     1.56400        -0.06           Q  Complete
4     1.92910         0.07           Q  Complete
5     2.49900         0.00           Q  Complete
6     1.82520         0.07           Q  Complete
...       ...          ...         ...       ...
2519  1.98720         0.01         TRB  Complete
2520  3.01032        -0.01         TRB  Complete
2521  5.24980        -0.25  PARAS-POLY  Complete
2527  7.38050        -0.08  PARAS-POLY  Complete
2528  3.88800         0.21  PARAS-POLY  Complete

[1476 rows x 16 columns]

In [17]:
# Get summary statistics
print(df.describe())

                     Po_Placing_Date         SO_No            NSR  \
count                           2529  2.529000e+03    2529.000000
mean   2025-09-16 11:58:34.590747136  1.934366e+07   80165.109529
min              2025-04-01 00:00:00  1.089586e+07   40000.000000
25%              2025-06-20 00:00:00  1.092050e+07   74000.000000
50%              2025-09-01 00:00:00  1.094027e+07   77000.000000
75%              2025-12-16 00:00:00  4.029709e+07   81000.000000
max              2026-03-31 00:00:00  8.487713e+07  189000.000000
std                              NaN  1.338527e+07   20988.414184

             VD_TPC          GSM        Width       Length       QTY-MT  \
count   1888.000000  2529.000000  2529.000000  1926.000000  2529.000000
mean    2246.689619   241.420720    70.216449    84.215421    12.034520
min      500.000000    28.000000    30.000000    44.500000     0.300000
25%     2000.000000   160.000000    58.500000    76.000000     2.500000
50%     2000.000000   285.000000    63.500000    89.000000     5.000000
75%     2250.000000   310.000000    78.700000    93.300000    13.000000
max    11250.000000   450.000000   213.500000   137.200000   500.000000
std     1772.936870   109.841954    21.790641    13.905625    28.629338

              DISP  Pending_Qty
count  2529.000000  2529.000000
mean     11.955451     0.079055
min       0.347300   -21.430000
25%       2.440200    -0.340000
50%       5.027400     0.000000
75%      13.167000     0.150000
max     495.777400   122.510000
std      27.763838     3.131395

In [18]:
df.to_csv('SS_DATA_PROJECT_cleaned.csv', index=False)  # Cleaned version

print("✅ Cleaned data saved as 'SS_DATA_PROJECT_cleaned.csv'")
print(f"Total rows: {df.shape[0]}")
print(f"Total columns: {df.shape[1]}")

✅ Cleaned data saved as 'SS_DATA_PROJECT_cleaned.csv'
Total rows: 2529
Total columns: 16

In [19]:
!pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector-python in c:\users\main\appdata\roaming\python\python313\site-packages (9.7.0)

In [20]:
# import pandas as pd
from sqlalchemy import create_engine
# Create connection to MySQL
engine = create_engine("mysql+pymysql://root:Nitish4298@localhost:3306/new_file")

# print("✅ MySQL connection created successfully!")

In [21]:
# Verify data from MySQL
df_verify = pd.read_sql("SELECT * FROM suneja_sons LIMIT 5", con=engine)

#print("✅ First 5 rows from MySQL table 'suneja_sons':")
#print(df_verify)

#print("\n✅ Column names in MySQL:")
#print(df_verify.columns.tolist())

#print(f"\n✅ Total rows in table: {len(pd.read_sql('SELECT COUNT(*) as count FROM suneja_sons', con=engine))}")

In [22]:
df.tail(10)

,Po_Placing_Date,PO_No,SO_No,Customer,Quality,NSR,VD_TPC,GSM,Width,Length,Grain,QTY-MT,DISP,Pending_Qty,PLANT,Status
2519,2026-03-11,SS4281,10964827,KAY ART PRINTER,PHARMA PRINT,120000,7000.0,38,63.5,91.5,LG,2.0,1.98720,0.01,TRB,Complete
2520,2026-03-11,SS4281,10964827,KAY ART PRINTER,PHARMA PRINT,120000,7000.0,38,58.5,91.5,LG,3.0,3.01032,-0.01,TRB,Complete
2521,2026-02-11,SS4148,10960054,SAPFOODPAK,INDOBEV BOARD 1PE,101500,NaN,177,77.5,NaN,REEL,5.0,5.24980,-0.25,PARAS-POLY,Complete
2522,2026-03-28,SS4365,10968450,Suneja Sons,CARTE LUMINA,80000,2000.0,350,53.3,78.7,LG,3.0,3.23400,-0.23,M,Complete
2523,2026-03-12,SS4293,10965213,Suneja Sons,ECO POLAR,53750,500.0,340,56.0,94.0,LG,1.5,1.39620,0.10,LEMIT,Complete
2524,2026-03-21,SS4343,10970371,SAPFOODPAK,INDOBEV 2 PE,120000,NaN,202,85.5,NaN,REEL,5.0,5.55050,-0.55,PARAS-POLY,Complete
2525,2026-03-31,SS4373,10970069,DJS PRINTER PVT LTD,INDOBEV 2 PE FSC,107000,NaN,327,87.0,64.0,SG,54.6,58.52694,-3.93,PARAS-POLY,Complete
2526,2026-03-31,SS4370,10976408,GLS FILMS INDUSTRIES,COATED BOARD CFK,100650,NaN,200,42.8,NaN,REEL,150.0,148.41100,1.59,M,Pending
2527,2026-03-31,SS4372,10970066,DJS PRINTER PVT LTD,INDOBEV 2 PE FSC,107000,NaN,252,99.0,58.0,SG,7.3,7.38050,-0.08,PARAS-POLY,Complete
2528,2026-03-31,SS4372,10970066,DJS PRINTER PVT LTD,INDOBEV 2 PE FSC,107000,NaN,252,80.0,67.0,SG,4.1,3.88800,0.21,PARAS-POLY,Complete